export const DEMO_PROPERTIES = [

  // ─── APARTMENTS (8) ──────────────────────────────────────────────────────────

  {
    id: 'demo-1',
    title: 'Modern 3BHK Apartment in Thamel',
    type: 'apartment',
    status: 'sale',
    price: 8500000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Thamel Marg, Ward 26, Kathmandu Metropolitan City',
    featured: true,
    listed_date: '2026-01-15',
    contact_phone: '+977-980-1234567',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
    ],
    features: ['Covered Parking', '24/7 Security', 'Balcony', 'Modern Kitchen', 'Backup Generator', 'Lift/Elevator'],
    description: `A beautifully designed 3-bedroom apartment on the 5th floor of a modern 8-storey building in the heart of Thamel, completed in 2023. The open-plan living area faces east with floor-to-ceiling windows, and the kitchen features granite countertops and modular cabinetry.

Two of the three bedrooms have attached bathrooms. The building offers covered parking, 24-hour CCTV security, and a standby generator. Located 200m from Thamel Chowk with easy access to restaurants, cafés, and major bus routes.

Ideal for families or investors — the Thamel corridor commands premium rental returns year-round.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-1234567', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-6',
    title: 'Furnished Studio near Pulchowk Campus',
    type: 'apartment',
    status: 'rent',
    price: 18000,
    bedrooms: 1,
    bathrooms: 1,
    area: 450,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Pulchowk Road, Ward 10, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-18',
    contact_phone: '+977-982-6601234',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    ],
    features: ['Fully Furnished', 'High-Speed WiFi Included', 'Security Guard', 'Rooftop Access', 'Walking Distance to IOE'],
    description: `A smartly furnished studio apartment on the 3rd floor just 300m from the IOE Pulchowk Campus. Designed for graduate students and young professionals, it features a partitioned sleeping area, built-in study desk, galley kitchen, and hot-water bathroom.

Fully furnished — bed, sofa, TV, desk, kitchen appliances all included. 100 Mbps fibre internet is included in the monthly rent. Building has a full-time security guard and inverter backup.

Pulchowk is one of Lalitpur's most connected localities with Patan Hospital, Mangal Bazar, and multiple bus routes all within 1 km.`,
    seller: { name: 'Priya Tamrakar', phone: '+977-982-6601234', email: 'priya.tamrakar@nepalestates.com', agency: 'NepalEstates Lalitpur Branch' },
  },

  {
    id: 'demo-7',
    title: '2BHK Apartment in Baneshwor',
    type: 'apartment',
    status: 'sale',
    price: 6200000,
    bedrooms: 2,
    bathrooms: 2,
    area: 950,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'New Baneshwor, Ward 34, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-02-20',
    contact_phone: '+977-981-2345678',
    images: [
      'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['Parking', 'Security', 'Balcony', 'Water Supply', 'Near Hospitals'],
    description: `A well-maintained 2-bedroom, 2-bathroom apartment on the 4th floor of a 6-storey building in New Baneshwor — one of Kathmandu's most accessible neighbourhoods. Both bedrooms are south-facing with natural light throughout the day.

The building is within walking distance of B&B Hospital, multiple schools, and Koteshwor bus terminal. One covered parking space included. Available for immediate possession.`,
    seller: { name: 'Deepak Paudel', phone: '+977-981-2345678', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-8',
    title: '1BHK Apartment for Rent in Sanepa',
    type: 'apartment',
    status: 'rent',
    price: 22000,
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Sanepa Height, Ward 17, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-01',
    contact_phone: '+977-984-3456789',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    ],
    features: ['Semi-Furnished', 'Parking', 'Security', 'Mountain View', 'Near Embassies'],
    description: `A bright 1-bedroom apartment in Sanepa Height — a quiet, tree-lined neighbourhood popular with diplomats and expats due to its proximity to several embassies. The apartment is semi-furnished with a bed, wardrobe, and kitchen fittings.

The living room balcony offers clear views toward the Shivapuri hills on clear mornings. Parking for one two-wheeler is available. A 10-minute drive from Patan Durbar Square.`,
    seller: { name: 'Sushma Khadka', phone: '+977-984-3456789', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Lalitpur Branch' },
  },

  {
    id: 'demo-9',
    title: 'Penthouse Apartment in Lazimpat',
    type: 'apartment',
    status: 'sale',
    price: 22000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2400,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Lazimpat Road, Ward 2, Kathmandu Metropolitan City',
    featured: true,
    listed_date: '2025-12-10',
    contact_phone: '+977-980-9876543',
    images: [
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
    ],
    features: ['Private Rooftop Terrace', 'Smart Home', 'Panoramic Views', 'Two Parking Spaces', 'Premium Finishes', 'Lift'],
    description: `An exceptional full-floor penthouse occupying the entire 10th floor of a premium residential tower in Lazimpat — Kathmandu's most prestigious address, home to numerous embassies and senior government officials.

The 2,400 sqft interior is finished to a specification rarely seen in Nepal: Italian marble flooring, Bosch appliances, automated lighting and climate control, and frameless glass balustrades on the wraparound terrace. Panoramic 360-degree views take in Swayambhunath, the valley rim, and the Himalayan skyline.

A truly once-in-a-generation offering in this location. Two dedicated parking spaces and a private storage room are included.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-980-9876543', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Premium Division' },
  },

  {
    id: 'demo-10',
    title: '2BHK Rental Apartment in Naxal',
    type: 'apartment',
    status: 'rent',
    price: 35000,
    bedrooms: 2,
    bathrooms: 2,
    area: 900,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Naxal Bhagawatibazar, Ward 4, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-04-05',
    contact_phone: '+977-985-4567890',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
      'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&q=80',
    ],
    features: ['Furnished', 'Parking', 'Security', 'Garden Access', 'Quiet Neighbourhood'],
    description: `A fully furnished 2-bedroom apartment in Naxal — a peaceful, upscale residential area just 10 minutes from Thamel and 5 minutes from Narayan Gopal Chowk. The apartment is on the 2nd floor with garden-level access from the living room.

Furnished with quality beds, sofas, dining set, refrigerator, washing machine, and kitchen fittings. Monthly rent includes water charges. Ideal for professionals or couples seeking a quiet central location.`,
    seller: { name: 'Binod Adhikari', phone: '+977-985-4567890', email: 'binod.adhikari@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-11',
    title: '3BHK Apartment in Chipledhunga, Pokhara',
    type: 'apartment',
    status: 'sale',
    price: 7800000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1100,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Chipledhunga, Ward 4, Pokhara Metropolitan City',
    featured: false,
    listed_date: '2026-02-14',
    contact_phone: '+977-986-5678901',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['Mountain View', 'Parking', 'Security', 'Balcony', 'Modern Kitchen'],
    description: `A spacious 3-bedroom apartment in Chipledhunga — Pokhara's main commercial hub — offering unobstructed views of the Annapurna range from the north-facing balcony. Built in 2022 with quality RCC construction and modern interiors.

Walking distance to Pokhara's main bazar, hospitals, and government offices. Chipledhunga bus park is 5 minutes away. A rare opportunity to own a mountain-view apartment in Nepal's fastest-growing city at a competitive price.`,
    seller: { name: 'Bikash Gurung', phone: '+977-986-5678901', email: 'bikash.gurung@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  {
    id: 'demo-12',
    title: 'Compact 1BHK in Mangal Bazar, Patan',
    type: 'apartment',
    status: 'rent',
    price: 16000,
    bedrooms: 1,
    bathrooms: 1,
    area: 520,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Mangal Bazar Road, Ward 18, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-10',
    contact_phone: '+977-982-6789012',
    images: [
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
    ],
    features: ['Partially Furnished', 'Water Included', 'Heritage Neighbourhood', 'Near Patan Durbar Square'],
    description: `A cosy 1-bedroom apartment steps from the UNESCO-listed Patan Durbar Square, in the heart of Mangal Bazar's vibrant artisan quarter. Perfect for solo professionals, artists, or travellers seeking long-term accommodation in a culturally rich setting.

Partially furnished with bed, wardrobe, and kitchen counter. Water charges included in rent. The area is lively day and night with restaurants, galleries, and traditional metalwork workshops nearby.`,
    seller: { name: 'Priya Tamrakar', phone: '+977-982-6789012', email: 'priya.tamrakar@nepalestates.com', agency: 'NepalEstates Lalitpur Branch' },
  },

  // ─── HOUSES (6) ──────────────────────────────────────────────────────────────

  {
    id: 'demo-3',
    title: 'Cozy 4BHK House near Fewa Lake',
    type: 'house',
    status: 'rent',
    price: 45000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Lakeside Road, Baidam, Ward 6, Pokhara Metropolitan City',
    featured: false,
    listed_date: '2026-02-10',
    contact_phone: '+977-986-5554433',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80',
    ],
    features: ['Lake View', 'Private Garden', 'Parking for 2 Cars', 'Furnished', 'Mountain View', 'Outdoor Seating'],
    description: `A charming fully-furnished four-bedroom house 150m from Fewa Lake in Pokhara's vibrant Lakeside district, renovated in 2024. The living room has large picture windows framing the Annapurna and Machhapuchchhre mountain ranges, and the dining area opens onto a private garden with covered outdoor seating.

Upstairs are four bedrooms, three with attached bathrooms, and the master bedroom has a private balcony with direct lake and mountain views.

Minimum 12-month lease. Two-month security deposit required. High-speed fibre internet and two covered parking spaces included.`,
    seller: { name: 'Bikash Gurung', phone: '+977-986-5554433', email: 'bikash.gurung@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  {
    id: 'demo-13',
    title: 'Traditional Newari House in Bhaktapur',
    type: 'house',
    status: 'sale',
    price: 18500000,
    bedrooms: 5,
    bathrooms: 3,
    area: 3200,
    area_unit: 'sqft',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Dattatraya Tole, Ward 3, Bhaktapur Municipality',
    featured: true,
    listed_date: '2026-01-05',
    contact_phone: '+977-985-3312211',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    ],
    features: ['Authentic Newari Architecture', 'Carved Woodwork', 'Courtyard', 'Rooftop Terrace', 'Heritage Zone', 'Clear Title'],
    description: `A rare and beautifully preserved traditional Newari house in the heart of Bhaktapur's UNESCO World Heritage Zone, just 100m from Dattatraya Temple. Built over 200 years ago and sensitively modernised, retaining original carved timber windows, latticed balconies, and a central courtyard.

Five bedrooms across three floors, with modern bathrooms, a fully-equipped kitchen, and a rooftop terrace with views toward Changu Narayan hill. The ground floor courtyard is a traditional sun-lit social space.

Ideal for heritage enthusiasts, boutique hotel conversion, or a discerning family home. A once-in-a-generation opportunity in one of Nepal's most historic neighbourhoods.`,
    seller: { name: 'Dipak Karmacharya', phone: '+977-985-3312211', email: 'dipak.karmacharya@nepalestates.com', agency: 'NepalEstates Bhaktapur Office' },
  },

  {
    id: 'demo-14',
    title: 'Modern House in Budhanilkantha',
    type: 'house',
    status: 'sale',
    price: 24000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3500,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Budhanilkantha, Ward 7, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-01-22',
    contact_phone: '+977-980-7890123',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    ],
    features: ['Mountain View', 'Solar Panels', 'Garden', 'Double Garage', 'Modern Kitchen', 'Quiet Area'],
    description: `A contemporary 4-bedroom standalone house set on an 8-aana plot in Budhanilkantha — one of Kathmandu's greenest and most peaceful northern suburbs, directly below the Shivapuri National Park. Built in 2020 with RCC construction, the home has clean modern lines, a wraparound garden, and mountain views from the upper floor.

Four bedrooms each with en-suite bathrooms, a large open-plan living-dining area, a chef's kitchen, and a double garage. Solar panels installed, cutting monthly electricity costs significantly. A 20-minute drive from Thamel on the Ring Road.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-7890123', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-15',
    title: '4BHK House for Rent in Imadol',
    type: 'house',
    status: 'rent',
    price: 55000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Imadol, Ward 22, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-12',
    contact_phone: '+977-984-8901234',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    ],
    features: ['Furnished', 'Parking for 2', 'Garden', 'Security', 'Near International Schools'],
    description: `A spacious furnished 4-bedroom house in Imadol — a popular residential area with many expat families, close to Sanepa and the international school belt. The house spans three floors with large rooms, a front garden, and parking for two cars.

Three of the four bedrooms have attached bathrooms. Furnished with quality furniture throughout. Near Lincoln School, Ullens School, and multiple international clinics. Available for immediate occupancy with a 12-month minimum lease.`,
    seller: { name: 'Sushma Khadka', phone: '+977-984-8901234', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Lalitpur Branch' },
  },

  {
    id: 'demo-16',
    title: '3BHK House in Lekhnath, Pokhara',
    type: 'house',
    status: 'sale',
    price: 14500000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2200,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Lekhnath Municipality, Ward 8, Kaski',
    featured: false,
    listed_date: '2026-02-28',
    contact_phone: '+977-986-9012345',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80',
    ],
    features: ['Lake View', 'Garden', 'Parking', 'Quiet Area', 'Near Highway'],
    description: `A well-built 3-bedroom house on a 6-aana plot in Lekhnath — a fast-developing suburb of Pokhara at the northern end of Phewa Lake, offering a quieter lifestyle while staying close to the city. The upper floor has partial lake views on clear days.

Three bedrooms with attached bathrooms, a modern kitchen, and a private garden with space for expansion. Located on a paved 16-foot road with easy access to the Prithvi Highway. Lekhnath is growing rapidly as Pokhara International Airport opens nearby.`,
    seller: { name: 'Bikash Gurung', phone: '+977-986-9012345', email: 'bikash.gurung@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  {
    id: 'demo-17',
    title: 'Family House in Dharan, Sunsari',
    type: 'house',
    status: 'sale',
    price: 9500000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2600,
    area_unit: 'sqft',
    city: 'Dharan',
    district: 'Sunsari',
    address: 'BP Chowk Area, Ward 11, Dharan Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-20',
    contact_phone: '+977-987-0123456',
    images: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
    ],
    features: ['Parking', 'Garden', 'Water Supply', 'Near Hospital', 'Quiet Street', 'Clear Title'],
    description: `A well-maintained 4-bedroom house in a quiet residential lane near BP Chowk in Dharan — Eastern Nepal's cleanest and most organised city, known for its pleasant hill-station climate and strong social infrastructure.

Three storeys with an open living room, large kitchen, and a garden. Located near BP Koirala Institute of Health Sciences (BPKIHS) and Dharan's main commercial area. Dharan is increasingly popular with professionals working in the eastern development region — excellent investment fundamentals.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-987-0123456', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  // ─── VILLAS (4) ──────────────────────────────────────────────────────────────

  {
    id: 'demo-2',
    title: 'Luxury 5BHK Villa with Garden & Pool',
    type: 'villa',
    status: 'sale',
    price: 35000000,
    bedrooms: 5,
    bathrooms: 4,
    area: 4200,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Jawalakhel, Ward 15, Lalitpur Sub-Metropolitan City',
    featured: true,
    listed_date: '2025-11-20',
    contact_phone: '+977-984-9876543',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
    ],
    features: ['Swimming Pool', 'Landscaped Garden', 'Double Garage', '24/7 Security', 'Home Theatre', 'Solar Panels', 'Smart Home System'],
    description: `An exceptional standalone villa on a 12-aana plot in prestigious Jawalakhel, Lalitpur. Built in 2021 to international standards, this five-bedroom residence combines privacy, luxury, and convenience.

The ground floor features a grand entrance foyer, formal living room, family lounge, chef's kitchen, and a guest bedroom opening onto a 2,000 sqft landscaped garden with a heated swimming pool. The top floor master suite has a private terrace with panoramic Boudhanath views, a spa bathroom, and two walk-in wardrobes.

A basement home theatre, smart home automation, solar panels covering 60% of electricity, a double garage, and caretaker's quarters complete this exceptional offering.`,
    seller: { name: 'Sunita Pradhan', phone: '+977-984-9876543', email: 'sunita.pradhan@nepalestates.com', agency: 'NepalEstates Premium Division' },
  },

  {
    id: 'demo-18',
    title: 'Hilltop Villa in Godavari',
    type: 'villa',
    status: 'sale',
    price: 28000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3800,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Godavari Village, Ward 2, Godavari Municipality',
    featured: true,
    listed_date: '2025-12-15',
    contact_phone: '+977-984-1234567',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    ],
    features: ['Valley Views', 'Organic Garden', 'Solar Power', 'Private Driveway', 'Koi Pond', 'Outdoor Pavilion'],
    description: `A magnificent hilltop villa on a 15-aana plot in serene Godavari, 10km south of Patan. Surrounded by botanical gardens and forests, this architect-designed home sits at 1,600m elevation with sweeping valley and Himalayan views from every room.

Four bedrooms, each with en-suite bathrooms and private balconies. A large open-plan living area flows to a wraparound terrace and outdoor pavilion. The organically managed terraced garden produces seasonal vegetables and herbs year-round.

Off-grid solar power covers 80% of energy needs. A rare private retreat for those who value nature and tranquillity without sacrificing quality.`,
    seller: { name: 'Sunita Pradhan', phone: '+977-984-1234567', email: 'sunita.pradhan@nepalestates.com', agency: 'NepalEstates Premium Division' },
  },

  {
    id: 'demo-19',
    title: 'Contemporary Villa in Bansbari',
    type: 'villa',
    status: 'sale',
    price: 42000000,
    bedrooms: 5,
    bathrooms: 5,
    area: 5200,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Bansbari, Ward 7, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2025-10-30',
    contact_phone: '+977-980-2345678',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
    ],
    features: ['Private Pool', 'Elevator', 'Smart Home', 'Five Parking Spaces', 'Staff Quarters', 'Panic Room', 'Rooftop Gym'],
    description: `Kathmandu's finest contemporary residential villa, set behind high walls on a 14-aana corner plot in Bansbari — a quiet enclave adjacent to the Central Zoo and favoured by senior diplomats and business leaders.

Spanning five floors including a basement, the villa features five lavish bedroom suites, a 50-foot private pool, rooftop gym, home cinema, wine cellar, and staff accommodation. Smart home technology controls lighting, security, HVAC, and entertainment across every room from a central app.

This is Kathmandu's most comprehensively specified residential offering at this price point. Viewings strictly by appointment.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-980-2345678', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Premium Division' },
  },

  {
    id: 'demo-20',
    title: 'Lakeside Villa for Rent in Phewa, Pokhara',
    type: 'villa',
    status: 'rent',
    price: 150000,
    bedrooms: 4,
    bathrooms: 4,
    area: 3600,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Phewa Taal Marg, Ward 6, Pokhara Metropolitan City',
    featured: false,
    listed_date: '2026-01-10',
    contact_phone: '+977-986-3456789',
    images: [
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
    ],
    features: ['Direct Lake Frontage', 'Private Jetty', 'Infinity Pool', 'Mountain View', 'Furnished', 'Caretaker Included'],
    description: `An exclusive lakefront villa on the shores of Phewa Lake — one of Nepal's most celebrated natural landmarks. This fully furnished four-bedroom retreat sits on a 12-aana plot with a private jetty, an infinity-edge pool, and unobstructed Machhapuchchhre views.

Available on a monthly rental basis ideal for corporate retreats, extended holidays, or high-net-worth expatriate accommodation. Includes full-time caretaker, weekly housekeeping, and a private rowboat. The Lakeside restaurant strip is a 5-minute walk.`,
    seller: { name: 'Bikash Gurung', phone: '+977-986-3456789', email: 'bikash.gurung@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  // ─── COMMERCIAL (6) ──────────────────────────────────────────────────────────

  {
    id: 'demo-4',
    title: 'Prime Commercial Space in New Road',
    type: 'commercial',
    status: 'rent',
    price: 120000,
    bedrooms: 0,
    bathrooms: 2,
    area: 1800,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'New Road Gate Area, Ward 23, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-03-05',
    contact_phone: '+977-981-7778899',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
    ],
    features: ['Ground Floor', 'Corner Unit', 'High Pedestrian Footfall', 'Wide Glass Frontage', 'Loading Dock', 'Basement Storage'],
    description: `A premium ground-floor commercial unit at the New Road Gate junction — Kathmandu's highest-footfall commercial corridor. The 1,800 sqft space has a 40-foot glass frontage, LED track lighting, climate control, and 400 sqft basement storage.

Suitable for retail showroom, pharmacy, bank branch, or restaurant. Electrical capacity 60 kVA. High-speed fibre conduit installed. Immediate availability, minimum 2-year lease.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-7778899', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-21',
    title: 'Showroom Space in Kalanki',
    type: 'commercial',
    status: 'rent',
    price: 95000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2200,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Kalanki Chowk, Ward 14, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-02-25',
    contact_phone: '+977-981-8901234',
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Ground Floor', 'Highway Frontage', 'High Traffic', 'Loading Access', 'Parking', 'Ring Road Location'],
    description: `A large ground-floor commercial space on the Ring Road at Kalanki Chowk — one of Kathmandu's busiest intersections connecting the city to the Prithvi and Tribhuvan highways. Ideal for automobile showrooms, electronics retailers, furniture stores, or logistics hubs.

Open floor plan of 2,200 sqft with high ceilings, wide loading access from the rear lane, and 6 car parking spaces. The location sees extremely high vehicle traffic from both directions of the Ring Road.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-8901234', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-22',
    title: 'Modern Office Floor in Hattisar',
    type: 'commercial',
    status: 'rent',
    price: 180000,
    bedrooms: 0,
    bathrooms: 3,
    area: 3500,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Hattisar, Ward 3, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-01-18',
    contact_phone: '+977-981-9012345',
    images: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
    ],
    features: ['Full Floor', 'Fibre Internet', 'Conference Rooms', 'Reception Area', 'Lift', 'Generator Backup', 'Parking for 10'],
    description: `An entire 3,500 sqft office floor in a Grade-A commercial building in Hattisar — Kathmandu's premier corporate address, home to international banks, IT companies, and multinational offices.

The space is fitted with a reception lobby, 8 private cabins, two conference rooms, an open workstation area for 50+ staff, a pantry, and three bathrooms. Lift access, generator backup, and 10 dedicated parking spaces. Ideal for corporate headquarters or branch offices.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-9012345', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-23',
    title: 'Retail Shop in Mangal Bazar, Lalitpur',
    type: 'commercial',
    status: 'rent',
    price: 65000,
    bedrooms: 0,
    bathrooms: 1,
    area: 800,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Mangal Bazar, Ward 18, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-28',
    contact_phone: '+977-981-0123456',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
    ],
    features: ['Tourist Area', 'Ground Floor', 'Display Windows', 'Heritage Zone', 'High Footfall'],
    description: `A ground-floor retail shop in Mangal Bazar, the commercial heart of Patan's UNESCO heritage zone. The shop has wide display windows facing the main pedestrian route between Patan Durbar Square and the Mangal Bazar shopping street — one of the most visited tourist corridors in the Kathmandu Valley.

800 sqft open floor plan, suitable for handicrafts, art gallery, café, or boutique fashion. Exceptionally high footfall from domestic and international visitors year-round.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-0123456', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-24',
    title: 'Warehouse & Storage Unit in Biratnagar',
    type: 'commercial',
    status: 'rent',
    price: 55000,
    bedrooms: 0,
    bathrooms: 2,
    area: 4500,
    area_unit: 'sqft',
    city: 'Biratnagar',
    district: 'Morang',
    address: 'Industrial Area, Ward 16, Biratnagar Metropolitan City',
    featured: false,
    listed_date: '2026-04-01',
    contact_phone: '+977-987-1234567',
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80',
    ],
    features: ['Heavy Duty Flooring', 'Loading Bay', 'High Ceiling (5m)', 'Security Cameras', 'Near Customs', 'Truck Access'],
    description: `A large industrial warehouse in Biratnagar's established industrial estate — Eastern Nepal's commercial capital and a major import/export hub with road links to India at Jogbani just 4km away.

4,500 sqft of clear-span warehouse space with 5m ceiling height, heavy-duty concrete flooring, a loading bay suitable for 40-ft containers, and full-time security. Ideal for manufacturing, warehousing, cold storage conversion, or logistics operations.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-987-1234567', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  {
    id: 'demo-25',
    title: 'Restaurant Space in Lakeside, Pokhara',
    type: 'commercial',
    status: 'rent',
    price: 80000,
    bedrooms: 0,
    bathrooms: 3,
    area: 2000,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Lakeside Road, Ward 6, Pokhara Metropolitan City',
    featured: false,
    listed_date: '2026-02-05',
    contact_phone: '+977-986-2345678',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
    ],
    features: ['Lake View Terrace', 'Commercial Kitchen', 'Tourist Strip', 'Outdoor Seating', 'Liquor Licence Zone'],
    description: `A prime restaurant and café space directly on the Lakeside tourist strip in Pokhara — Nepal's most visited destination outside Kathmandu. The two-floor space has a ground-floor indoor dining area, a fitted commercial kitchen, and an upper-floor open terrace with views across Phewa Lake to the Annapurna range.

The location puts you directly in the path of thousands of trekkers and tourists daily. The kitchen is partially equipped. The area falls within Pokhara's designated liquor licence zone. This is arguably the best vacant F&B site on the entire strip.`,
    seller: { name: 'Bikash Gurung', phone: '+977-986-2345678', email: 'bikash.gurung@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  // ─── LAND (6) ────────────────────────────────────────────────────────────────

  {
    id: 'demo-5',
    title: 'Residential Plot in Suryamadhi, Bhaktapur',
    type: 'land',
    status: 'sale',
    price: 12000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 8,
    area_unit: 'aana',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Suryamadhi Tole, Ward 5, Bhaktapur Municipality',
    featured: false,
    listed_date: '2026-01-28',
    contact_phone: '+977-985-3312211',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Road Access (20ft)', 'Clear Title (Lalpurja)', 'Residential Zone', 'Municipal Water', 'Corner Plot'],
    description: `A corner residential plot of 8 aana (4,072 sqft) in Suryamadhi Tole — a rapidly developing Bhaktapur locality with strong infrastructure investment. Level rectangular plot with 20-foot road frontage, municipal water and electricity at the boundary, and clean Lalpurja title.

Soil test confirms suitability for a 4-storey RCC structure. 2.5km from Bhaktapur Durbar Square and 1.8km from the expressway on-ramp. No loans or encumbrances. Phased payment of up to 6 months considered.`,
    seller: { name: 'Dipak Karmacharya', phone: '+977-985-3312211', email: 'dipak.karmacharya@nepalestates.com', agency: 'NepalEstates Bhaktapur Office' },
  },

  {
    id: 'demo-26',
    title: 'Residential Plot in Tokha, Kathmandu',
    type: 'land',
    status: 'sale',
    price: 9500000,
    bedrooms: 0,
    bathrooms: 0,
    area: 6,
    area_unit: 'aana',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Tokha Municipality, Ward 4, Kathmandu',
    featured: false,
    listed_date: '2026-02-18',
    contact_phone: '+977-980-3456789',
    images: [
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['16ft Road Access', 'Residential Zone', 'Mountain View', 'Water Supply', 'Clear Title'],
    description: `A well-located 6-aana residential plot in Tokha Municipality on Kathmandu's northern fringe — a leafy, rapidly growing suburb known for its cooler climate and Himalayan views. On a 16-foot paved road with municipal water at the boundary and power lines overhead.

The plot is flat and rectangular, well-suited for a 3–4 storey home. Mountain views from upper floors guaranteed. Tokha is 7km from central Kathmandu, with regular micro-bus service. A perfect plot for those seeking a calm residential setting close to the city.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-3456789', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-27',
    title: 'Agricultural Land in Chitwan',
    type: 'land',
    status: 'sale',
    price: 6500000,
    bedrooms: 0,
    bathrooms: 0,
    area: 20,
    area_unit: 'aana',
    city: 'Chitwan',
    district: 'Chitwan',
    address: 'Bharatpur Metropolitan City, Ward 19, Chitwan',
    featured: false,
    listed_date: '2026-03-08',
    contact_phone: '+977-984-4567890',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['Flat Land', 'Canal Irrigation', 'Fertile Soil', 'Road Access', 'Near Highway', 'Agricultural Zone'],
    description: `A productive 20-aana (10,172 sqft) agricultural plot in Bharatpur — the capital of Chitwan and one of Nepal's most fertile Terai districts. Currently under rice and mustard cultivation with a functional canal irrigation connection.

Flat, stone-free land with black cotton soil — ideal for commercial farming, agro-tourism, or long-term land banking in a fast-developing city. Bharatpur is now Nepal's 5th largest city, with strong infrastructure growth and road access to both Kathmandu (4 hrs) and Butwal.`,
    seller: { name: 'Deepak Paudel', phone: '+977-984-4567890', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-28',
    title: 'Commercial Plot in Chabahil, Kathmandu',
    type: 'land',
    status: 'sale',
    price: 32000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 10,
    area_unit: 'aana',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Chabahil Ganesh Tole, Ward 6, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2025-12-20',
    contact_phone: '+977-980-4567890',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Commercial Zone', '24ft Road Frontage', 'Near Boudhanath', 'High Footfall', 'Development Potential'],
    description: `A prime 10-aana commercially-zoned plot on the main Chabahil road — one of the busiest connecting arteries between Boudhanath Stupa (UNESCO) and central Kathmandu. The plot has 24-foot road frontage and is classified as commercial land under Kathmandu Metropolitan City's zoning plan, allowing up to 6 floors.

Chabahil is a densely populated commercial zone with daily footfall in the tens of thousands. Suitable for mixed-use hotel/retail/office development. A rare plot of this size, zoning, and location to come onto the open market.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-4567890', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-29',
    title: 'Land for Sale in Kirtipur',
    type: 'land',
    status: 'sale',
    price: 7200000,
    bedrooms: 0,
    bathrooms: 0,
    area: 5,
    area_unit: 'aana',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Kirtipur Municipality, Ward 8, Kathmandu District',
    featured: false,
    listed_date: '2026-04-12',
    contact_phone: '+977-985-5678901',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    ],
    features: ['Valley Views', '12ft Road Access', 'Residential Zone', 'Quiet Area', 'Near TU Campus'],
    description: `A 5-aana residential plot in Kirtipur — a hilltop municipality with a rich cultural heritage, just 5km from Kathmandu city centre. The plot is on a gentle slope with open valley views and a clear 12-foot approach road.

Close to Tribhuvan University, making it ideal for student housing development. Kirtipur's elevated position gives excellent air quality and temperatures several degrees cooler than the valley floor. Clear Lalpurja, no encumbrances.`,
    seller: { name: 'Deepak Paudel', phone: '+977-985-5678901', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-30',
    title: 'Residential Plot in Dharan, Sunsari',
    type: 'land',
    status: 'sale',
    price: 4800000,
    bedrooms: 0,
    bathrooms: 0,
    area: 7,
    area_unit: 'aana',
    city: 'Dharan',
    district: 'Sunsari',
    address: 'Bijayapur, Ward 14, Dharan Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-25',
    contact_phone: '+977-987-6789012',
    images: [
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['Level Plot', '16ft Road Access', 'Residential Zone', 'Water & Power', 'Near BPKIHS'],
    description: `A level 7-aana residential plot in Bijayapur — a fast-growing residential zone of Dharan, Eastern Nepal's cleanest hill city. Municipal water and electricity lines are connected at the plot boundary, and a 16-foot paved road provides excellent access.

Located 1.5km from BP Koirala Institute of Health Sciences (BPKIHS), the plot appeals to medical staff, students, and professionals relocating to Dharan. Dharan's pleasant climate, strong civic infrastructure, and Eastern Highway connectivity make it one of Nepal's best cities for residential investment.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-987-6789012', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  // ─── NEW APARTMENTS (4, total 12) ────────────────────────────────────────────

  {
    id: 'demo-31',
    title: '2BHK Apartment near Boudhanath Stupa',
    type: 'apartment',
    status: 'sale',
    price: 7200000,
    bedrooms: 2,
    bathrooms: 2,
    area: 880,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Bauddha, Ward 6, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-04-20',
    contact_phone: '+977-980-5678901',
    images: [
      'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
    ],
    features: ['Near Boudhanath', 'Parking', 'Security', 'Balcony', 'Water Supply'],
    description: `A well-maintained 2-bedroom apartment just 400m from the iconic Boudhanath Stupa — one of the world's largest Buddhist stupas and a UNESCO World Heritage Site. The apartment is on the 3rd floor of a 5-storey building with a south-facing balcony.

Both bedrooms have built-in wardrobes and natural ventilation. The kitchen has granite countertops and modern fittings. Covered parking for one vehicle is included.

Bouddha is a cosmopolitan, peaceful neighbourhood popular with Tibetan, expat, and Buddhist communities. Multiple cafés, monasteries, international schools, and health clinics are within walking distance.`,
    seller: { name: 'Binod Adhikari', phone: '+977-980-5678901', email: 'binod.adhikari@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-32',
    title: '1BHK Apartment for Rent in Gongabu',
    type: 'apartment',
    status: 'rent',
    price: 20000,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Gongabu Bus Park Area, Ward 29, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-04-25',
    contact_phone: '+977-985-6789012',
    images: [
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    ],
    features: ['Near Bus Park', 'Partially Furnished', 'Security', 'Water Included', 'Easy Commute'],
    description: `A tidy 1-bedroom apartment in Gongabu — home to Kathmandu's main long-distance bus terminal. Ideal for commuters, students, and young professionals who need fast intercity travel access. The apartment is on the 2nd floor with a private balcony.

Partially furnished with a bed frame, wardrobe, and kitchen counter. Water charges included in monthly rent. Public buses to all major city destinations depart from Gongabu Bus Park just 200m away.

Close to Machhapokhari, Ring Road, and a growing number of restaurants and retail shops.`,
    seller: { name: 'Deepak Paudel', phone: '+977-985-6789012', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-33',
    title: '3BHK Apartment in Butwal, Rupandehi',
    type: 'apartment',
    status: 'sale',
    price: 5500000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1050,
    area_unit: 'sqft',
    city: 'Butwal',
    district: 'Rupandehi',
    address: 'Traffic Chowk Area, Ward 8, Butwal Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-30',
    contact_phone: '+977-971-1234567',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['Parking', 'Security', 'Balcony', 'Modern Kitchen', 'Near Highway'],
    description: `A modern 3-bedroom apartment on the 4th floor of a new building near Traffic Chowk in Butwal — the commercial gateway to Nepal's western Terai and a major trade hub on the Siddhartha Highway. The apartment features an open living area, modular kitchen, and a balcony facing the Palpa hills.

Both attached bathrooms have premium sanitary fittings. Covered parking for one vehicle. Located near Butwal's main bazaar, banks, and the Siddhartha Highway junction that connects to Pokhara and Kathmandu.

Butwal is one of Nepal's fastest-growing cities, making this an excellent investment opportunity at a competitive price.`,
    seller: { name: 'Sushma Khadka', phone: '+977-971-1234567', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Western Branch' },
  },

  {
    id: 'demo-34',
    title: '2BHK Apartment for Rent in Birgunj',
    type: 'apartment',
    status: 'rent',
    price: 25000,
    bedrooms: 2,
    bathrooms: 2,
    area: 800,
    area_unit: 'sqft',
    city: 'Birgunj',
    district: 'Parsa',
    address: 'Ghantaghar Road, Ward 7, Birgunj Metropolitan City',
    featured: false,
    listed_date: '2026-04-08',
    contact_phone: '+977-951-2345678',
    images: [
      'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
    ],
    features: ['Air Conditioning', 'Parking', 'Security', 'Near Market', 'Generator Backup'],
    description: `A comfortable 2-bedroom apartment near Ghantaghar in Birgunj — Nepal's most important industrial and trade city, situated on the border with India. Air-conditioned bedrooms make Terai summers comfortable, and the building has a generator for uninterrupted power during load-shedding.

Both bedrooms have attached bathrooms. Covered parking for one vehicle included. The apartment is close to Birgunj's main commercial district, customs office, and the India–Nepal Raxaul–Birgunj border crossing.

Ideal for business travellers, traders, and corporate employees stationed in Birgunj.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-951-2345678', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  // ─── NEW HOUSES (4, total 10) ─────────────────────────────────────────────────

  {
    id: 'demo-35',
    title: '4BHK House in Kapan, Kathmandu',
    type: 'house',
    status: 'sale',
    price: 19000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 3000,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Kapan, Ward 5, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-01-10',
    contact_phone: '+977-980-6789012',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    ],
    features: ['Garden', 'Parking', 'Solar Panels', 'Mountain View', 'Quiet Area', 'Near Monastery'],
    description: `A well-designed 4-bedroom house on a 7-aana plot in Kapan — a peaceful, rapidly developing suburb of Kathmandu best known for the large Kapan Monastery. The house is three storeys with a garden, solar panels, and clear mountain views from the top floor.

Three bedrooms have attached bathrooms; the fourth is served by a shared bathroom. A large kitchen leads to the garden, which has space for an outdoor seating area. Solar panels cover daytime electricity needs.

Kapan sits between Bouddha and Tokha on Kathmandu's northern side — increasingly popular with families seeking a quieter, greener lifestyle close to the city.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-6789012', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-36',
    title: '4BHK House for Sale in Hetauda',
    type: 'house',
    status: 'sale',
    price: 11000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2800,
    area_unit: 'sqft',
    city: 'Hetauda',
    district: 'Makwanpur',
    address: 'Narayani Zone, Ward 5, Hetauda Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-14',
    contact_phone: '+977-957-1234567',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&q=80',
    ],
    features: ['Garden', 'Parking', 'Water Supply', 'Clear Title', 'Highway Access', 'Industrial Zone Proximity'],
    description: `A solidly built 4-bedroom house on a 10-aana plot in Hetauda — the industrial capital of Bagmati Province and a strategically located city at the crossroads of the BP Highway connecting the Terai to Kathmandu.

Three floors with a flat roof suitable for additional construction. Large garden with fruit trees. Hetauda is home to numerous national and multinational manufacturing plants, making it ideal for professionals working in the industrial sector.

A 2-hour drive from Kathmandu on the BP Highway. Excellent investment as Hetauda's importance as an industrial city grows with new road and energy infrastructure.`,
    seller: { name: 'Deepak Paudel', phone: '+977-957-1234567', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-37',
    title: '3BHK House for Rent in Itahari',
    type: 'house',
    status: 'rent',
    price: 40000,
    bedrooms: 3,
    bathrooms: 2,
    area: 2200,
    area_unit: 'sqft',
    city: 'Itahari',
    district: 'Sunsari',
    address: 'Itahari Chowk, Ward 3, Itahari Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-02',
    contact_phone: '+977-977-2345678',
    images: [
      'https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1200&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=1200&q=80',
    ],
    features: ['Furnished', 'Parking', 'Garden', 'Near Schools', 'Security', 'Highway Access'],
    description: `A furnished 3-bedroom house near Itahari Chowk — the major commercial and transport hub of the eastern Terai, situated at the junction of the East–West Highway and the Dharan–Dhankuta road. A perfect base for families and professionals working in the eastern development region.

Three bedrooms with two bathrooms, a furnished living room, dining area, and kitchen. Small garden at the front. Excellent connectivity to Biratnagar (25km), Dharan (15km), and Dhankuta.

Itahari is a rapidly expanding city with growing retail, education, and health infrastructure — one of Eastern Nepal's most dynamic urban centres.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-977-2345678', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  {
    id: 'demo-38',
    title: '3BHK House in Suryabinayak, Bhaktapur',
    type: 'house',
    status: 'sale',
    price: 16000000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2400,
    area_unit: 'sqft',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Suryabinayak, Ward 8, Bhaktapur Municipality',
    featured: false,
    listed_date: '2026-02-08',
    contact_phone: '+977-985-7890123',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=1200&q=80',
    ],
    features: ['Garden', 'Parking', 'Balcony', 'Valley View', 'Near Expressway', 'Modern Design'],
    description: `A modern 3-bedroom house on a 6-aana plot in Suryabinayak — a fast-developing locality in Bhaktapur just 1km from the Kathmandu–Bhaktapur expressway on-ramp, making it highly accessible from Kathmandu (25 minutes) and the airport (20 minutes).

Each of the three bedrooms has an attached bathroom. A wrap-around balcony on the top floor offers views of the valley and nearby hills. The well-maintained garden has space for a car and children's play area.

Suryabinayak is home to a major temple, several industrial zones, and new residential developments — an emerging hotspot with strong investment fundamentals.`,
    seller: { name: 'Dipak Karmacharya', phone: '+977-985-7890123', email: 'dipak.karmacharya@nepalestates.com', agency: 'NepalEstates Bhaktapur Office' },
  },

  // ─── NEW VILLAS (2, total 6) ─────────────────────────────────────────────────

  {
    id: 'demo-39',
    title: 'Luxury Villa in Dhulikhel with Himalayan Views',
    type: 'villa',
    status: 'sale',
    price: 32000000,
    bedrooms: 4,
    bathrooms: 4,
    area: 4000,
    area_unit: 'sqft',
    city: 'Dhulikhel',
    district: 'Kavrepalanchowk',
    address: 'Dhulikhel Municipality, Ward 2, Kavrepalanchowk',
    featured: true,
    listed_date: '2026-01-05',
    contact_phone: '+977-980-7654321',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80',
    ],
    features: ['Himalayan Panorama', 'Infinity Pool', 'Large Garden', 'Solar Power', 'Private Driveway', 'Organic Farm'],
    description: `A breathtaking architect-designed villa perched on a ridge above Dhulikhel at 1,550m elevation — with arguably the finest unobstructed Himalayan panorama in the Kathmandu Valley. The 270-degree view sweeps from Langtang in the west to Gauri Shankar in the east, spanning over 80km of the Himalayan range.

Four spacious bedroom suites each with private terraces, an infinity-edge pool overlooking the mountains, a large organic kitchen garden, and off-grid solar power. The villa's interiors combine local stone and timber with contemporary design in a way that honours the landscape without dominating it.

Dhulikhel is 30km from Kathmandu on the Araniko Highway — 45 minutes on a clear day. Dhulikhel Hospital (internationally accredited) is 10 minutes away.`,
    seller: { name: 'Sunita Pradhan', phone: '+977-980-7654321', email: 'sunita.pradhan@nepalestates.com', agency: 'NepalEstates Premium Division' },
  },

  {
    id: 'demo-40',
    title: 'Mountain Resort Villa in Nagarkot',
    type: 'villa',
    status: 'rent',
    price: 100000,
    bedrooms: 3,
    bathrooms: 3,
    area: 2800,
    area_unit: 'sqft',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Nagarkot Hill, Ward 2, Bhaktapur Municipality',
    featured: false,
    listed_date: '2026-02-01',
    contact_phone: '+977-985-8901234',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=1200&q=80',
      'https://images.unsplash.com/photo-1416331108676-a22ccb276e35?w=1200&q=80',
    ],
    features: ['Himalayan Panorama', 'Sunrise Views', 'Fully Furnished', 'Fireplace', 'Outdoor Terrace', 'Caretaker'],
    description: `A cosy but luxurious mountain villa at 2,175m in Nagarkot — one of Nepal's most celebrated sunrise viewpoints, perched on the eastern rim of the Kathmandu Valley. The fully furnished three-bedroom villa has a stone fireplace, wraparound terrace, and unobstructed views of Everest, Lhotse, Makalu, and the full Himalayan arc.

Available for long-term monthly rental. Includes a full-time caretaker and weekly housekeeping. Nagarkot is 32km from Kathmandu — 1 hour by road. A rare and tranquil retreat for those who want to live in the Himalayas while staying accessible.`,
    seller: { name: 'Dipak Karmacharya', phone: '+977-985-8901234', email: 'dipak.karmacharya@nepalestates.com', agency: 'NepalEstates Bhaktapur Office' },
  },

  // ─── NEW COMMERCIAL (4, total 10) ────────────────────────────────────────────

  {
    id: 'demo-41',
    title: 'Office Space in Putalisadak, Kathmandu',
    type: 'commercial',
    status: 'rent',
    price: 150000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2800,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Putalisadak, Ward 34, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-02-12',
    contact_phone: '+977-981-1234567',
    images: [
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=1200&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
    ],
    features: ['Central Location', 'Lift', 'Fibre Internet', 'Generator Backup', 'Conference Room', 'Parking for 8'],
    description: `A fully fitted office floor on the 3rd floor of a modern commercial building on Putalisadak — one of Kathmandu's most central and well-connected business corridors, equidistant from Thamel, Lazimpat, and Durbar Marg.

2,800 sqft with a furnished reception, 6 private offices, 1 large conference room, an open workstation area for 30+ staff, pantry, and 2 bathrooms. Dedicated fibre internet conduit, generator backup, and 8 dedicated parking spaces. Immediate availability. Minimum 2-year lease.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-1234567', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-42',
    title: 'Commercial Space in Birgunj City Centre',
    type: 'commercial',
    status: 'rent',
    price: 75000,
    bedrooms: 0,
    bathrooms: 2,
    area: 1600,
    area_unit: 'sqft',
    city: 'Birgunj',
    district: 'Parsa',
    address: 'Ghantaghar Road, Ward 5, Birgunj Metropolitan City',
    featured: false,
    listed_date: '2026-03-22',
    contact_phone: '+977-951-3456789',
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
    ],
    features: ['Ground Floor', 'High Footfall', 'Wide Frontage', 'Near Customs', 'Generator Backup', 'Parking'],
    description: `A prominent ground-floor commercial space on Ghantaghar Road — the main commercial artery of Birgunj, Nepal's busiest border trade city. High daily footfall from traders, customs agents, and retail shoppers.

1,600 sqft open plan with a wide frontage and display windows. Generator backup ensures no power interruption. Suitable for banking, retail, pharma distribution, or import/export office. Located 800m from the Birgunj Integrated Check Post (ICP) — the main India–Nepal customs crossing.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-951-3456789', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  {
    id: 'demo-43',
    title: 'Retail Space in Butwal Bazar',
    type: 'commercial',
    status: 'rent',
    price: 55000,
    bedrooms: 0,
    bathrooms: 1,
    area: 1000,
    area_unit: 'sqft',
    city: 'Butwal',
    district: 'Rupandehi',
    address: 'Butwal Bazar, Ward 9, Butwal Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-15',
    contact_phone: '+977-971-3456789',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Ground Floor', 'Main Bazar Location', 'High Footfall', 'Display Windows', 'Near Bus Terminal'],
    description: `A ground-floor retail shop in Butwal's main bazar — the commercial heart of western Nepal's most important trade city. Butwal is the primary distribution hub for goods moving between Kathmandu, Pokhara, Lumbini, and the Indian border at Nautanwa.

1,000 sqft open floor plan with wide display windows. Suitable for pharma, grocery, clothing, electronics, or services. High daily footfall from local residents and transit traders. 300m from Butwal bus terminal.`,
    seller: { name: 'Sushma Khadka', phone: '+977-971-3456789', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Western Branch' },
  },

  {
    id: 'demo-44',
    title: 'Showroom Space in Sukedhara, Kathmandu',
    type: 'commercial',
    status: 'rent',
    price: 70000,
    bedrooms: 0,
    bathrooms: 1,
    area: 1400,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Sukedhara, Ward 7, Kathmandu Metropolitan City',
    featured: false,
    listed_date: '2026-03-05',
    contact_phone: '+977-981-2345678',
    images: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Ground Floor', 'Showroom Layout', 'Parking', 'Main Road Frontage', 'Storage Room'],
    description: `A spacious showroom unit on the ground floor of a commercial complex in Sukedhara — a key northern residential and commercial node linking Lazimpat, Bansbari, and Bouddha. Excellent visibility from the main road with a 30-foot glass frontage.

1,400 sqft showroom with a rear storage room, dedicated parking for 3 cars, and high ceilings suited for product display. Well-suited for furniture, electronics, fitness equipment, or automotive accessories. Immediate availability.`,
    seller: { name: 'Anjali Maharjan', phone: '+977-981-2345678', email: 'anjali.maharjan@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  // ─── NEW LAND (6, total 12) ───────────────────────────────────────────────────

  {
    id: 'demo-45',
    title: 'Residential Plot in Sankhu, Kathmandu',
    type: 'land',
    status: 'sale',
    price: 8000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 10,
    area_unit: 'aana',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Sankhu, Ward 3, Shankharapur Municipality',
    featured: false,
    listed_date: '2026-04-18',
    contact_phone: '+977-980-8901234',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
    ],
    features: ['20ft Road Access', 'Residential Zone', 'Mountain View', 'Water Supply', 'Peaceful Area'],
    description: `A 10-aana residential plot on the outskirts of Sankhu — an ancient Newari trading town on Kathmandu's northeastern edge, known for the Vajrayogini Temple and peaceful rural atmosphere. The plot is on a gentle slope with mountain views and a 20-foot paved approach road.

Municipal water supply and electricity at the boundary. Clean Lalpurja with no encumbrances. Land prices in Sankhu have risen consistently as the outer Kathmandu ring road and urban expansion push outward. An excellent value land investment in a scenic setting.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-8901234', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-46',
    title: 'Land for Sale in Hetauda, Makwanpur',
    type: 'land',
    status: 'sale',
    price: 5500000,
    bedrooms: 0,
    bathrooms: 0,
    area: 12,
    area_unit: 'aana',
    city: 'Hetauda',
    district: 'Makwanpur',
    address: 'Puspalal Chowk Area, Ward 9, Hetauda Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-18',
    contact_phone: '+977-957-2345678',
    images: [
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['Level Plot', '16ft Road Access', 'Residential Zone', 'Near Industrial Estate', 'Water & Power'],
    description: `A level 12-aana residential plot near Puspalal Chowk in Hetauda — the industrially significant capital of Makwanpur district at the junction of the BP and Mahendra highways. Municipal water and electricity connections at the boundary. 16-foot road access.

Hetauda is known for the Hetauda Industrial District — one of Nepal's oldest industrial estates — and its strategic position as a midpoint between Kathmandu and the Terai. Land values here are growing steadily as industrial employment drives residential demand.`,
    seller: { name: 'Deepak Paudel', phone: '+977-957-2345678', email: 'deepak.paudel@nepalestates.com', agency: 'NepalEstates Central Office' },
  },

  {
    id: 'demo-47',
    title: 'Plot for Sale in Itahari, Sunsari',
    type: 'land',
    status: 'sale',
    price: 5000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 8,
    area_unit: 'aana',
    city: 'Itahari',
    district: 'Sunsari',
    address: 'East-West Highway Zone, Ward 6, Itahari Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-05',
    contact_phone: '+977-977-3456789',
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Level Plot', 'Near Highway', 'Residential Zone', 'Water Supply', 'Clear Title'],
    description: `An 8-aana level residential plot near the East–West Highway in Itahari — the emerging commercial powerhouse of Sunsari district, strategically located at the convergence of major eastern highway routes. Municipal water connected; electricity line overhead.

Itahari's economy is powered by wholesale trade, agro-processing, and its role as a transit hub for eastern Nepal. Land values here have nearly doubled in the past 5 years as urbanisation accelerates. Clear Lalpurja, no disputes, immediate transfer.`,
    seller: { name: 'Arun Bajracharya', phone: '+977-977-3456789', email: 'arun.bajracharya@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  {
    id: 'demo-48',
    title: 'Residential Land in Bhairahawa, Rupandehi',
    type: 'land',
    status: 'sale',
    price: 9000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 11,
    area_unit: 'aana',
    city: 'Bhairahawa',
    district: 'Rupandehi',
    address: 'Siddharthanagar Municipality, Ward 12, Rupandehi',
    featured: false,
    listed_date: '2026-02-22',
    contact_phone: '+977-971-4567890',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['Level Plot', '20ft Road Access', 'Near Airport', 'Commercial Zone Proximity', 'Water & Power'],
    description: `An 11-aana level residential plot in Bhairahawa (Siddharthanagar) — the commercial capital of western Nepal and home to Gautam Buddha International Airport, one of Nepal's newest and most significant international airports. The plot is on a 20-foot paved road with full utility connections.

Bhairahawa is the gateway to Lumbini (27km), birthplace of Gautam Buddha, and a growing industrial zone with apparel manufacturing, agro-processing, and logistics. The new international airport and Lumbini tourism expansion are driving land values rapidly upward.`,
    seller: { name: 'Sushma Khadka', phone: '+977-971-4567890', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Western Branch' },
  },

  {
    id: 'demo-49',
    title: 'Prime Land for Sale in Thankot, Kathmandu',
    type: 'land',
    status: 'sale',
    price: 11000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 9,
    area_unit: 'aana',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Thankot, Ward 1, Chandragiri Municipality',
    featured: false,
    listed_date: '2026-04-28',
    contact_phone: '+977-980-9012345',
    images: [
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1200&q=80',
    ],
    features: ['Prithvi Highway Frontage', 'Valley Views', 'Residential Zone', 'Development Potential', '16ft Road'],
    description: `A prime 9-aana plot in Thankot — the western gateway to Kathmandu on the Prithvi Highway, 12km from central Kathmandu. The plot has direct Prithvi Highway frontage and commanding valley views looking east toward Swayambhunath and the city.

Thankot is increasingly popular as a residential and commercial hub for those working in Kathmandu but seeking larger plots at lower prices than the inner city. The Chandragiri Hills cable car station is 3km away, adding tourism and leisure value to the area.`,
    seller: { name: 'Ramesh Shrestha', phone: '+977-980-9012345', email: 'ramesh.shrestha@nepalestates.com', agency: 'NepalEstates Thamel Office' },
  },

  {
    id: 'demo-50',
    title: 'Scenic Land for Sale in Tansen, Palpa',
    type: 'land',
    status: 'sale',
    price: 3500000,
    bedrooms: 0,
    bathrooms: 0,
    area: 8,
    area_unit: 'aana',
    city: 'Tansen',
    district: 'Palpa',
    address: 'Tansen Municipality, Ward 4, Palpa',
    featured: false,
    listed_date: '2026-04-22',
    contact_phone: '+977-975-1234567',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Valley Views', '12ft Road Access', 'Residential Zone', 'Hill Town', 'Scenic Location'],
    description: `An 8-aana residential plot in Tansen — one of Nepal's most charming hill towns in Palpa district, perched at 1,370m on a ridge overlooking the Kali Gandaki valley. Tansen is famous for its Newari architecture, dhaka weaving, metalwork, and peaceful lifestyle — increasingly popular with retirees and remote workers.

The plot is on a 12-foot road with open valley views and a clean Lalpurja. Tansen is 4 hours from Kathmandu and 1 hour from Butwal. An affordable entry into one of Nepal's most aesthetically distinctive and historically rich locations.`,
    seller: { name: 'Sushma Khadka', phone: '+977-975-1234567', email: 'sushma.khadka@nepalestates.com', agency: 'NepalEstates Western Branch' },
  },

  // ─── NEW 20 PROPERTIES (DIFFERENT LOCATIONS) ────────────────────────────────────

  {
    id: 'demo-41',
    title: 'Modern Penthouse in Bhaktapur',
    type: 'apartment',
    status: 'sale',
    price: 12000000,
    bedrooms: 4,
    bathrooms: 3,
    area: 1800,
    area_unit: 'sqft',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Nakkhu Marg, Ward 5, Bhaktapur Metropolitan City',
    featured: true,
    listed_date: '2026-04-10',
    contact_phone: '+977-983-1234567',
    images: [
      'https://images.unsplash.com/photo-1505873242700-f289a29e7e0f?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['City View', 'Modern Kitchen', 'Gym', 'Swimming Pool', 'Lift/Elevator', 'Rooftop Terrace'],
    description: `An exquisite 4-bedroom penthouse on the 10th floor of a luxury development in Bhaktapur. Offering panoramic views of the Kathmandu Valley and the Himalayas on clear days. Premium finishes throughout with energy-efficient systems. Building includes a fitness center, infinity pool, and 24/7 security.`,
    seller: { name: 'Vikram Singh', phone: '+977-983-1234567', email: 'vikram.singh@nepalestates.com', agency: 'NepalEstates Premium Properties' },
  },

  {
    id: 'demo-42',
    title: '2BHK Cozy Home in Pokhara',
    type: 'house',
    status: 'sale',
    price: 7500000,
    bedrooms: 2,
    bathrooms: 2,
    area: 1100,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Lakeside Road, Ward 12, Pokhara Metropolitan City',
    featured: false,
    listed_date: '2026-04-12',
    contact_phone: '+977-984-2345678',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    ],
    features: ['Lake View', 'Garden', 'Parking', 'Water Supply', 'Natural Light'],
    description: `A charming 2-bedroom house overlooking Phewa Lake in Pokhara. Perfect for a peaceful retirement or vacation retreat. Features a spacious garden ideal for morning walks while enjoying mountain views. Close to Lakeside restaurants and shops.`,
    seller: { name: 'Hari Prasad Baral', phone: '+977-984-2345678', email: 'hari.baral@nepalestates.com', agency: 'NepalEstates Pokhara Branch' },
  },

  {
    id: 'demo-43',
    title: 'Commercial Space in Biratnagar',
    type: 'commercial',
    status: 'sale',
    price: 15000000,
    bedrooms: 0,
    bathrooms: 2,
    area: 2500,
    area_unit: 'sqft',
    city: 'Biratnagar',
    district: 'Morang',
    address: 'Main Bazaar, Ward 8, Biratnagar Metropolitan City',
    featured: false,
    listed_date: '2026-04-08',
    contact_phone: '+977-985-3456789',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['High Foot Traffic', 'Attached Warehouse', 'Security Cameras', 'Three-Phase Electricity'],
    description: `A prime commercial space on the main bazaar in Biratnagar. Ideal for retail stores, supermarkets, or business offices. High visibility and foot traffic. The space includes an attached warehouse and modern security systems.`,
    seller: { name: 'Mahendra Thapa', phone: '+977-985-3456789', email: 'mahendra.thapa@nepalestates.com', agency: 'NepalEstates Commercial Division' },
  },

  {
    id: 'demo-44',
    title: 'Budget Apartment in Janakpur',
    type: 'apartment',
    status: 'rent',
    price: 12000,
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    area_unit: 'sqft',
    city: 'Janakpur',
    district: 'Dhanusa',
    address: 'Dhanusha Road, Ward 3, Janakpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-05',
    contact_phone: '+977-986-4567890',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    ],
    features: ['Furnished', 'WiFi Included', 'Security Guard', 'Water Supply', 'Near School'],
    description: `An affordable furnished apartment in Janakpur, ideal for students and young professionals. Walking distance from Janakpur Railway Station and the famous Janaki Mandir temple. WiFi and water supply included in rent.`,
    seller: { name: 'Sarita Kumari', phone: '+977-986-4567890', email: 'sarita.kumari@nepalestates.com', agency: 'NepalEstates Janakpur Office' },
  },

  {
    id: 'demo-45',
    title: '3BHK Villa in Butwal',
    type: 'villa',
    status: 'sale',
    price: 9800000,
    bedrooms: 3,
    bathrooms: 3,
    area: 1500,
    area_unit: 'sqft',
    city: 'Butwal',
    district: 'Rupandehi',
    address: 'Ramkot Marg, Ward 15, Butwal Sub-Metropolitan City',
    featured: true,
    listed_date: '2026-04-02',
    contact_phone: '+977-987-5678901',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
    ],
    features: ['Garden', 'Private Parking', 'Security Wall', 'Water Harvesting', 'Solar Panels'],
    description: `A beautiful 3-bedroom villa in Butwal with eco-friendly features. The villa includes a private garden, water harvesting system, and solar panels for energy efficiency. Perfect for families seeking a modern yet sustainable living space in this growing city.`,
    seller: { name: 'Ravi Kumar Joshi', phone: '+977-987-5678901', email: 'ravi.joshi@nepalestates.com', agency: 'NepalEstates Western Properties' },
  },

  {
    id: 'demo-46',
    title: 'Industrial Plot in Birgunj',
    type: 'land',
    status: 'sale',
    price: 25000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 5000,
    area_unit: 'sqft',
    city: 'Birgunj',
    district: 'Parsa',
    address: 'Industrial Zone, Ward 10, Birgunj Metropolitan City',
    featured: false,
    listed_date: '2026-04-01',
    contact_phone: '+977-988-6789012',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Industrial Zoning', 'Good Road Access', 'Three-Phase Electricity', 'Near Highway'],
    description: `A spacious industrial plot in Birgunj's designated industrial zone. Well-connected by road with access to three-phase electricity. Perfect for setting up manufacturing units, warehouses, or distribution centers.`,
    seller: { name: 'Ajay Sinha', phone: '+977-988-6789012', email: 'ajay.sinha@nepalestates.com', agency: 'NepalEstates Industrial Properties' },
  },

  {
    id: 'demo-47',
    title: 'Luxurious Apartment in Dharan',
    type: 'apartment',
    status: 'sale',
    price: 11500000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1400,
    area_unit: 'sqft',
    city: 'Dharan',
    district: 'Sunsari',
    address: 'New Market, Ward 7, Dharan Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-28',
    contact_phone: '+977-989-7890123',
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['Modern Amenities', 'Rooftop Garden', 'Backup Generator', 'Security System', 'Lift/Elevator'],
    description: `A sophisticated 3-bedroom apartment in the heart of Dharan's New Market area. Modern design with premium fittings. Building amenities include a rooftop garden, 24-hour backup power, and CCTV security throughout.`,
    seller: { name: 'Naresh Yadav', phone: '+977-989-7890123', email: 'naresh.yadav@nepalestates.com', agency: 'NepalEstates Eastern Branch' },
  },

  {
    id: 'demo-48',
    title: 'Budget Flat in Nepalgunj',
    type: 'apartment',
    status: 'rent',
    price: 16000,
    bedrooms: 1,
    bathrooms: 1,
    area: 550,
    area_unit: 'sqft',
    city: 'Nepalgunj',
    district: 'Banke',
    address: 'Bageshwori Road, Ward 6, Nepalgunj Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-25',
    contact_phone: '+977-990-8901234',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
    ],
    features: ['Furnished', 'Nearby School', 'Market Access', 'Water Tank', 'Street Lights'],
    description: `A comfortable 1-bedroom furnished apartment in Nepalgunj. Located near local schools and markets with easy access to transportation. Reliable water supply and community security in place.`,
    seller: { name: 'Deepa Dahal', phone: '+977-990-8901234', email: 'deepa.dahal@nepalestates.com', agency: 'NepalEstates Banke Office' },
  },

  {
    id: 'demo-49',
    title: 'Premium Office Space in Itahari',
    type: 'commercial',
    status: 'rent',
    price: 45000,
    bedrooms: 0,
    bathrooms: 2,
    area: 1200,
    area_unit: 'sqft',
    city: 'Itahari',
    district: 'Sunsari',
    address: 'Main Junction, Ward 4, Itahari Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-22',
    contact_phone: '+977-991-9012345',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Prime Location', 'Modern Amenities', 'Parking', 'Backup Power', 'Internet Ready'],
    description: `A professional office space at Itahari's main junction. Perfect for corporate offices, consultancies, or service centers. Fully equipped with modern amenities, parking facilities, and backup power systems.`,
    seller: { name: 'Sunil Kumar Singh', phone: '+977-991-9012345', email: 'sunil.singh@nepalestates.com', agency: 'NepalEstates Commercial Rentals' },
  },

  {
    id: 'demo-50',
    title: 'Cozy Family Home in Dhangadi',
    type: 'house',
    status: 'sale',
    price: 8900000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1300,
    area_unit: 'sqft',
    city: 'Dhangadi',
    district: 'Kailali',
    address: 'Mahendranagar Road, Ward 9, Dhangadi Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-20',
    contact_phone: '+977-992-0123456',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
    ],
    features: ['Family-Friendly', 'Spacious Yard', 'Good School Access', 'Market Proximity', 'Safety Gate'],
    description: `A comfortable 3-bedroom house in a family-friendly neighborhood in Dhangadi. Located near quality schools and local markets. The property includes a spacious yard perfect for gardening and outdoor activities.`,
    seller: { name: 'Pradeep Saha', phone: '+977-992-0123456', email: 'pradeep.saha@nepalestates.com', agency: 'NepalEstates Far Western Branch' },
  },

  {
    id: 'demo-51',
    title: 'Upscale Penthouse in Kathmandu Valley View',
    type: 'apartment',
    status: 'sale',
    price: 16800000,
    bedrooms: 4,
    bathrooms: 3,
    area: 2000,
    area_unit: 'sqft',
    city: 'Kathmandu',
    district: 'Kathmandu',
    address: 'Maharajgunj, Ward 1, Kathmandu Metropolitan City',
    featured: true,
    listed_date: '2026-04-11',
    contact_phone: '+977-980-5555555',
    images: [
      'https://images.unsplash.com/photo-1505873242700-f289a29e7e0f?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Valley View', 'Gym', 'Rooftop Lounge', 'Concierge Service', 'Smart Home'],
    description: `An exceptional penthouse apartment in prestigious Maharajgunj offering panoramic Kathmandu Valley views. Smart home technology, concierge service, gym, and rooftop lounge. A truly luxurious living experience in Nepal's capital.`,
    seller: { name: 'Govinda Lama', phone: '+977-980-5555555', email: 'govinda.lama@nepalestates.com', agency: 'NepalEstates Luxury Collection' },
  },

  {
    id: 'demo-52',
    title: '1BHK Studio in Lalitpur',
    type: 'apartment',
    status: 'rent',
    price: 20000,
    bedrooms: 1,
    bathrooms: 1,
    area: 600,
    area_unit: 'sqft',
    city: 'Lalitpur',
    district: 'Lalitpur',
    address: 'Imadol, Ward 12, Lalitpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-04-09',
    contact_phone: '+977-982-6666666',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=1200&q=80',
    ],
    features: ['Fully Furnished', 'WiFi Included', 'Parking', 'Water Supply', 'Community Garden'],
    description: `A modern furnished studio apartment in Lalitpur's growing Imadol area. Perfect for working professionals. Includes WiFi, water supply, and a community garden. Walking distance to shops and restaurants.`,
    seller: { name: 'Anita Shrestha', phone: '+977-982-6666666', email: 'anita.shrestha@nepalestates.com', agency: 'NepalEstates Lalitpur Studio Collection' },
  },

  {
    id: 'demo-53',
    title: 'Residential Plot in Bhaktapur',
    type: 'land',
    status: 'sale',
    price: 6500000,
    bedrooms: 0,
    bathrooms: 0,
    area: 3000,
    area_unit: 'sqft',
    city: 'Bhaktapur',
    district: 'Bhaktapur',
    address: 'Dumbarton, Ward 2, Bhaktapur Metropolitan City',
    featured: false,
    listed_date: '2026-04-06',
    contact_phone: '+977-983-7777777',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Clear Ownership', 'Good Road Access', 'Residential Zone', 'Scenic View', 'Corner Plot'],
    description: `A well-located residential plot in Bhaktapur's Dumbarton area with scenic valley views. Clear ownership documents and good road access. Ideal for building a dream home away from the hustle of central Kathmandu.`,
    seller: { name: 'Kiran Manandhar', phone: '+977-983-7777777', email: 'kiran.manandhar@nepalestates.com', agency: 'NepalEstates Land Division' },
  },

  {
    id: 'demo-54',
    title: 'Lakeside Cottage in Pokhara',
    type: 'house',
    status: 'rent',
    price: 35000,
    bedrooms: 2,
    bathrooms: 1,
    area: 900,
    area_unit: 'sqft',
    city: 'Pokhara',
    district: 'Kaski',
    address: 'Lakeside, Ward 2, Pokhara Metropolitan City',
    featured: true,
    listed_date: '2026-04-03',
    contact_phone: '+977-984-8888888',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    ],
    features: ['Lake View', 'Tourist Area', 'Restaurant Nearby', 'Mountain View', 'Travel Package'],
    description: `A charming lakeside cottage in Pokhara's tourist area. Stunning views of Phewa Lake and Annapurna mountains. Perfect for tourists, short-term stays, or holiday rentals. Close to restaurants, shops, and water activities.`,
    seller: { name: 'Dawa Sherpa', phone: '+977-984-8888888', email: 'dawa.sherpa@nepalestates.com', agency: 'NepalEstates Tourism Properties' },
  },

  {
    id: 'demo-55',
    title: 'Modern Retail Store in Biratnagar',
    type: 'commercial',
    status: 'sale',
    price: 18500000,
    bedrooms: 0,
    bathrooms: 1,
    area: 2000,
    area_unit: 'sqft',
    city: 'Biratnagar',
    district: 'Morang',
    address: 'Biratnagar Bazaar, Ward 1, Biratnagar Metropolitan City',
    featured: false,
    listed_date: '2026-03-30',
    contact_phone: '+977-985-9999999',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['High Traffic', 'Multiple Storey', 'Storage Room', 'Security Camera', 'Prime Location'],
    description: `A multi-storey modern retail complex in Biratnagar's bustling bazaar area. High foot traffic and excellent visibility. Features a storage room and modern security systems. Perfect for retail business expansion.`,
    seller: { name: 'Raj Kumar Sharma', phone: '+977-985-9999999', email: 'raj.sharma@nepalestates.com', agency: 'NepalEstates Retail Properties' },
  },

  {
    id: 'demo-56',
    title: 'Sacred Temple-View Apartment in Janakpur',
    type: 'apartment',
    status: 'sale',
    price: 4500000,
    bedrooms: 2,
    bathrooms: 1,
    area: 750,
    area_unit: 'sqft',
    city: 'Janakpur',
    district: 'Dhanusa',
    address: 'Janaki Nagar, Ward 1, Janakpur Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-27',
    contact_phone: '+977-986-1111111',
    images: [
      'https://images.unsplash.com/photo-1535221228889-3e64c4a89bb0?w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=1200&q=80',
    ],
    features: ['Temple View', 'Spiritual Location', 'Good Ventilation', 'Water Supply', 'Parking'],
    description: `A 2-bedroom apartment in the sacred Janaki Nagar area of Janakpur with views of the famous Janaki Mandir temple. A peaceful location for spiritual seekers and families. Good ventilation and natural light throughout the apartment.`,
    seller: { name: 'Sundari Singh', phone: '+977-986-1111111', email: 'sundari.singh@nepalestates.com', agency: 'NepalEstates Sacred Properties' },
  },

  {
    id: 'demo-57',
    title: 'Eco-Friendly Villa in Butwal',
    type: 'villa',
    status: 'rent',
    price: 65000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1600,
    area_unit: 'sqft',
    city: 'Butwal',
    district: 'Rupandehi',
    address: 'Tilottama, Ward 6, Butwal Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-24',
    contact_phone: '+977-987-2222222',
    images: [
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
    ],
    features: ['Solar Powered', 'Organic Garden', 'Rain Water Harvesting', 'Recycled Materials', 'Meditation Room'],
    description: `An eco-friendly villa in Tilottama area of Butwal with sustainable living features. Solar power system, rainwater harvesting, and organic garden for self-sufficiency. A meditation room for wellness. Perfect for environmentally conscious families.`,
    seller: { name: 'Parvati Acharya', phone: '+977-987-2222222', email: 'parvati.acharya@nepalestates.com', agency: 'NepalEstates Eco Properties' },
  },

  {
    id: 'demo-58',
    title: 'Agricultural Land in Birgunj',
    type: 'land',
    status: 'sale',
    price: 8000000,
    bedrooms: 0,
    bathrooms: 0,
    area: 10000,
    area_unit: 'sqft',
    city: 'Birgunj',
    district: 'Parsa',
    address: 'Pakaha, Ward 5, Birgunj Metropolitan City',
    featured: false,
    listed_date: '2026-03-21',
    contact_phone: '+977-988-3333333',
    images: [
      'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&q=80',
      'https://images.unsplash.com/photo-1464082354059-27db6ce50048?w=1200&q=80',
    ],
    features: ['Fertile Land', 'Water Source', 'Good Soil', 'Irrigation Facility', 'Accessible Road'],
    description: `A fertile agricultural land in Pakaha area near Birgunj. Suitable for farming, cultivation, or investment. Good soil quality with access to water sources and irrigation facilities. Accessible by good road for easy agricultural operations.`,
    seller: { name: 'Bhagwan Das Yadav', phone: '+977-988-3333333', email: 'bhagwan.das@nepalestates.com', agency: 'NepalEstates Agricultural Land Division' },
  },

  {
    id: 'demo-59',
    title: 'Business Complex in Dharan',
    type: 'commercial',
    status: 'sale',
    price: 21000000,
    bedrooms: 0,
    bathrooms: 3,
    area: 3500,
    area_unit: 'sqft',
    city: 'Dharan',
    district: 'Sunsari',
    address: 'Bazaar Center, Ward 1, Dharan Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-18',
    contact_phone: '+977-989-4444444',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Four Storeys', 'Elevator', 'Commercial & Residential', 'Basement Parking', 'Modern Architecture'],
    description: `A four-storey commercial complex in the heart of Dharan's bazaar center. Perfect for multi-purpose business use with retail shops on ground floor and office/residential spaces above. Includes basement parking and modern architectural design with elevator facility.`,
    seller: { name: 'Amar Thapa', phone: '+977-989-4444444', email: 'amar.thapa@nepalestates.com', agency: 'NepalEstates Commercial Complex Division' },
  },

  {
    id: 'demo-60',
    title: 'Budget Friendly Apartment in Nepalgunj',
    type: 'apartment',
    status: 'sale',
    price: 3800000,
    bedrooms: 1,
    bathrooms: 1,
    area: 480,
    area_unit: 'sqft',
    city: 'Nepalgunj',
    district: 'Banke',
    address: 'Nepalgunj Bazaar, Ward 2, Nepalgunj Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-15',
    contact_phone: '+977-990-5555555',
    images: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=1200&q=80',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=1200&q=80',
    ],
    features: ['Affordable', 'Market Area', 'Easy Access', 'Water & Electricity', 'Simple Design'],
    description: `An affordable 1-bedroom apartment in the Bazaar area of Nepalgunj. Perfect first home for young couples or budget-conscious buyers. Located near markets with easy access to public transportation. All basic utilities included.`,
    seller: { name: 'Mina Adhikari', phone: '+977-990-5555555', email: 'mina.adhikari@nepalestates.com', agency: 'NepalEstates Budget Properties' },
  },

  {
    id: 'demo-61',
    title: 'Tech Hub Office Space in Itahari',
    type: 'commercial',
    status: 'rent',
    price: 55000,
    bedrooms: 0,
    bathrooms: 2,
    area: 1500,
    area_unit: 'sqft',
    city: 'Itahari',
    district: 'Sunsari',
    address: 'Tech Park, Ward 3, Itahari Sub-Metropolitan City',
    featured: true,
    listed_date: '2026-04-04',
    contact_phone: '+977-991-6666666',
    images: [
      'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&q=80',
    ],
    features: ['Tech Ready', 'High Speed Internet', 'Meeting Rooms', 'Open Plan', 'Community Space'],
    description: `A modern tech hub office space in Itahari's growing tech park. Purpose-built for startups and IT companies with high-speed fiber internet, meeting rooms, and open-plan workspace. Community spaces for collaboration and innovation.`,
    seller: { name: 'Samrat Karmacharya', phone: '+977-991-6666666', email: 'samrat.k@nepalestates.com', agency: 'NepalEstates Tech Properties' },
  },

  {
    id: 'demo-62',
    title: 'Traditional House in Dhangadi',
    type: 'house',
    status: 'rent',
    price: 28000,
    bedrooms: 3,
    bathrooms: 2,
    area: 1200,
    area_unit: 'sqft',
    city: 'Dhangadi',
    district: 'Kailali',
    address: 'Residential Area, Ward 4, Dhangadi Sub-Metropolitan City',
    featured: false,
    listed_date: '2026-03-12',
    contact_phone: '+977-992-7777777',
    images: [
      'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=1200&q=80',
      'https://images.unsplash.com/photo-1570129477492-45a003cf3ce1?w=1200&q=80',
    ],
    features: ['Traditional Design', 'Large Courtyard', 'Multiple Rooms', 'Well Water', 'Peaceful Area'],
    description: `A beautiful traditional-style house in a peaceful residential area of Dhangadi. Features traditional design with modern amenities. Large courtyard perfect for gatherings and outdoor activities. Well water supply and spacious rooms throughout.`,
    seller: { name: 'Bishnu Subedi', phone: '+977-992-7777777', email: 'bishnu.subedi@nepalestates.com', agency: 'NepalEstates Traditional Properties' },
  },
];
